apiVersion: apps/v1
kind: Deployment
metadata:
  name: celery-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: celery
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: giorgi023/projects:v1
        command: ["celery", "-A", "src.celery_worker", "worker", "--loglevel=info"]
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: db-uri-secret
              key: uri
