apiVersion: batch/v1
kind: Job
metadata:
  name: migration-job
spec:
  template:
    spec:
      containers:
      - name: migration
        image: giorgi023/projects:v1
        env:
        - name: DB_URI
          valueFrom:
            secretKeyRef:
              name: db-uri-secret
              key: uri
        command: ["alembic", "upgrade", "head"]  
      restartPolicy: OnFailure  
