apiVersion: v1
kind: Secret
metadata:
  name: db-uri-secret
type: Opaque
data:
  uri: |
    cG9zdGdyZXNxbCthc3luY3BnOi8vZ2lvcmdpOmdpb3JnaTE5OTBAcG9zdGdyZXM6NTQzMi9tb2xl
    Y3VsZXM=
---
apiVersion: v1
kind: Secret
metadata:
  name: db-user-secret
type: Opaque
data:
  username: Z2lvcmdp
---
apiVersion: v1
kind: Secret
metadata:
  name: db-password-secret
type: Opaque
data:
  password: Z2lvcmdpMTk5MA==
---
apiVersion: v1
kind: Secret
metadata:
  name: db-name-secret
type: Opaque
data:
  database: bW9sZWN1bGVz
